### ISSUE TITLE
Error while installing the package

### ISSUE THREAD

**Issue by ashkanrdn** [SimScaleGmbH/topo_extend#19]
HI I'm getting this error when trying to install the package: 
\ashkan.radnia\appdata\local\temp\pip-req-build-0nkqx7bj
  Running command git clone --filter=blob:none --quiet https://github.com/DHLynch/topo_extend.git 'C:\Users\Ashkan.Radnia\AppData\Local\Temp\pip-req-build-0nkqx7bj'
  Resolved https://github.com/DHLynch/topo_extend.git to commit dd2dd2be7e117e3932c3405f99c354c8e2f380eb
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pathlib (from topoExtend==0.1.dev193+gdd2dd2b)
  Using cached pathlib-1.0.1-py3-none-any.whl (14 kB)
INFO: pip is looking at multiple versions of topoextend to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement open3d (from topoextend) (from versions: none)
ERROR: No matching distribution found for open3d

**Comment by DHLynch** [comment]
Hi @ashkanrdn, thanks for raising this. Open3d does not support Python version 3.11, the only version I could reproduce this in. I added an exception to the installation process, telling you to use Python 3.10. I will remove the restriction when it is supported. 

Best,
Darren

**Comment by DHLynch** [comment]
Closing this, but feel free to raise another if you are still struggling.
